### ISSUE TITLE
Error en la cadena de texto de los likes

### ISSUE THREAD

**Issue by iamdarkle** [flarum-lang/spanish#7]
La cadena de texto se repite:

![22222](https://user-images.githubusercontent.com/15818451/125148952-347ca680-e136-11eb-98be-0ff001653f3f.PNG)

**Comment by jslirola** [comment]
Hola @iamdarkle ¿solucionaste esto? He encontrado casos similares pero no sé cómo traducirlo sin "romper" los plurales:

![imagen](https://user-images.githubusercontent.com/6697559/131558984-10503d7c-cce7-403f-9ce4-1f4f095659dd.png)

**Comment by iamdarkle** [comment]
Pues creía que lo había solucionado, pero claro solo me había fijado en el caso específico de cuando varios usuarios le dan like, quedaban más cadenas (las he marcado para edición https://weblate.rob006.net/translate/flarum/flarum-likes/es/?checksum=8a1d1f57560cc90a). La original es **_{users} like this_**, la verdad que no tengo ni idea de cómo traducirlo... Es que claro el 'Tú' es global se utiliza en más sitios como en el ejemplo de arriba de la foto y si se borra {users} para que no aparezca el 'Tú' luego como otro usuario o invitado no aparece el nombre 🤔

Pues hay que echarle un vistazo y ver si repiten casos así, para avisar y ver como se maneja, imagino que en otros idiomas también debe dar problemas esto.

**Comment by jslirola** [comment]
He indagado un poco y veo que en la traducción de italiano han solventado en problema con los plurares con un formato específico: https://weblate.rob006.net/translate/flarum/flarum-mentions/it/?checksum=dee8fba3a058a273

Así que he hecho unas pruebas en local y parece que se diferencia fácilmente cuando se aplica al singular y plural.

```
{count, plural, one {{users} respondió a esto.} other {{users} respondieron a esto.}}

{count, plural, one {{users} respondiste a esto.} other {{users} respond\u00edsteis a esto.}}

{count, plural, one {A {users} te gusta esto.} other {A {users} os gusta esto.}}
```

![imagen](https://user-images.githubusercontent.com/6697559/132137495-ffb2ecb5-0c04-4648-b494-d0b7a196c9c1.png)

Nos queda localizar las traducciones que apliquen los dos formatos y pensar qué hacer con el "Tú" en ciertos casos.

**Comment by jslirola** [comment]
Actualizadas las siguientes cadenas para solucionar duplicidades, por ir solucionando algunas cosas. Aun quedará pendiente el tema del "Tú".

flarum-mentions:
https://weblate.rob006.net/translate/flarum/flarum-mentions/es/?checksum=1b89ee6741be5cc6
https://weblate.rob006.net/translate/flarum/flarum-mentions/es/?checksum=e86a39d05a7c4e26
https://weblate.rob006.net/translate/flarum/flarum-mentions/es/?checksum=dee8fba3a058a273

flarum-likes:
https://weblate.rob006.net/translate/flarum/flarum-likes/es/?checksum=7fb4d49e73f93e2d
https://weblate.rob006.net/translate/flarum/flarum-likes/es/?checksum=8a1d1f57560cc90a

**Comment by iamdarkle** [comment]
¡Muchas gracias! Ya está publicada la 1.1.4 con los cambios.

He recordado que todo esto de los duplicados fue por el cambio a ICU MessageFormat, me suena que algún traductor puso en su momento un post con todas las cadenas que necesitaban cambios, a ver si lo consigo encontrar y así cerramos este tema, ya no creo queden muchas.

Lo del "Tú" probablemente lo comentaré en 'flarum/core' no tengo muy claro que se pueda solucionar fácilmente... 😕
